apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aht60h98i-nodejs 
  janus-idp.io/tekton: aht60h98i-nodejs
  backstage.io/kubernetes-id: aht60h98i-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aht60h98i-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  